language: cpp

os: linux
sudo: true


before_script:
  - chmod +x build-setup.sh
  - chmod +x pack-resources.sh
  - ./build-setup.sh
  - ./pack-resources.sh

script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" ..
  - make