language: cpp
compiler: gcc

os: linux
dist: trusty
sudo: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake

before_install:
  - chmod +x build-setup-deb.sh
  - chmod +x pack-resources.sh
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - gcc -v
  - g++ -v
  - cmake --version

install:
  - bash -x build-setup-deb.sh

before_script:
  - bash -x pack-resources.sh

script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make